[package]
name = "matthewclayrusso_com"
edition = "2021"
version = "0.1.0"
authors = ["Matthew Russo <matthew@matthewclayrusso.com>"]

[dependencies]
http-body-util = "0.1.0-rc.2" 
hyper = { version = "1.0.0-rc.3", features = ["full"] }
tokio = { version = "1", features = ["full"] }
